
spring:
  redis:
    host: 192.168.142.128
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 30000
    database: 0
server:
  port: 9001
